jobs:

- job: VS_Latest

  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: GitVersion@3
    inputs:
      updateAssemblyInfo: false   
      
  - task: NuGetToolInstaller@0
    inputs:
        versionSpec: 4.7.0
        checkLatest: false

  - task: MSBuild@1
    inputs:
      solution: BikeSharing.Xamarin-UWP.sln
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: /r /p:Configuration=Release "/p:PackageVersion=%GITVERSION_FullSemVer%" "/p:InformationalVersion=%GITVERSION_InformationalVersion%" /detailedsummary
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false

  - task: PublishBuildArtifacts@1
    displayName: Publish Wasm Artifacts
    inputs:
      pathToPublish: .\src\BikeSharing.Clients.WASM\bin\Release\netstandard2.0\dist
      artifactType: container
      artifactName: BikeSharing-Wasm